# License: GNU GPL version 3 <https://www.gnu.org/licenses/gpl-3.0.html>
# Copyright (C) 2021  Author: Alex Shirshov <https://github.com/Whywolk>

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booksDB
    username: postgres
    password: anosore
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /
  port: 8081
  address: 127.0.0.1